Parameters:
    EnvironmentName:
        Type: String
        Description: "The environment name as a prefix"
    # New Bucket name
    MyBucketName:
        Description: "Existing Bucket name"
        Type: String
Resources:
    WebsiteBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref MyBucketName
            AccessControl: "PublicRead"
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: error.html

    WebsiteBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket:
                Ref: "WebsiteBucket"
            PolicyDocument:
                Statement:
                    -   Sid: PublicReadForGetBucketObjects
                        Effect: Allow
                        Principal: '*'
                        Action: s3:GetObject
                        Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref 'WebsiteBucket', /* ] ]

Outputs:
    WebsiteURL:
        Description: "S3 static host endpoint"
        Value:
            Fn::GetAtt:
                - WebsiteBucket
                - WebsiteURL
