# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # Exercise: Smoke Testing
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: 
          name: "Install cUrl"
          command: |
            "apk add --update curl"
      - run:
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  create-infrastructure-workflow:
    jobs:
      - create_network
      - create_security:
          requires:
            - "create_network"
      - create_launch_template:
          requires:
            - "create_security"
      - create_ec2_instances:
          requires:
            - "create_launch_template"
      - add_publicipaddress_to_inventory:
          requires:
            - "create_ec2_instances"
      - configure_infrastructure:
          requires:
            - "add_publicipaddress_to_inventory"
